spring:
  profiles:
    active: dev

  datasource:
    dirver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgirl
    username: root
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true